
from math import ceil

#Quanto as requisicoes
BANDWIDTH    :list[int]   = [100, 150, 200, 250, 300, 350, 400]
CLASS_TYPE   :list[float] = [1, 2, 3]
CLASS_WEIGHT :list[float] = [0.15, 0.25, 0.60]

HOLDING_TIME :float       = 1

#Quando a topologia
NUMERO_DE_SLOTS    :int   = 200
NUMERO_DE_CAMINHOS :int   = 20
SLOT_SIZE          :float = 12.5


__NUMERO_DE_EDGES_DA_TOPOLOGIA: int = 43
__CAPACIDADE_MAXIMA_DA_REDE: int = NUMERO_DE_SLOTS * __NUMERO_DE_EDGES_DA_TOPOLOGIA 
__MEDIA_REQUISICAO_BANDWIDTH: float = sum(BANDWIDTH)/len(BANDWIDTH)
__MEDIA_MODULACAO: float = 1.0601449275362318
__MEDIA_SLOTS_REQUISITADOS_POR_REQUISICAO: float = ceil(__MEDIA_REQUISICAO_BANDWIDTH / (SLOT_SIZE * __MEDIA_MODULACAO))

#parametrizar por erlang
PORCENTAGEM_ALVO_DA_REDE_REQUISITADA_POR_SEGUNDO: float = 0.25
DURACAO_ALVO_DA_SIMULACAO: float = 2000
__REQUISICOES_POR_SEGUNDO :float = PORCENTAGEM_ALVO_DA_REDE_REQUISITADA_POR_SEGUNDO * __CAPACIDADE_MAXIMA_DA_REDE/__MEDIA_SLOTS_REQUISITADOS_POR_REQUISICAO
__NUMERO_DE_REQUISICOES :int = ceil(__REQUISICOES_POR_SEGUNDO * DURACAO_ALVO_DA_SIMULACAO)
#Quanto a simulação
REQUISICOES_POR_SEGUNDO :float = __REQUISICOES_POR_SEGUNDO
NUMERO_DE_REQUISICOES   :int   = __NUMERO_DE_REQUISICOES
NUMERO_DE_ISPS          :int   = 5

#Quanto aos datacenters
#THROUGHPUT                   :float = REQUISITADO_DA_REDE_POR_SEGUNDO * 0.025
THROUGHPUT                   :float = __CAPACIDADE_MAXIMA_DA_REDE * 0.025
VARIANCIA_THROUGPUT          :float = THROUGHPUT * 0.1
TEMPO_DE_REACAO              :float = 600
VARIANCIA_TEMPO_DE_REACAO    :float = 90
TAMANHO_DATACENTER           :float = THROUGHPUT * 300
VARIANCIA_TAMANHO_DATACENTER :float = TAMANHO_DATACENTER * 0.1


